### ISSUE TITLE
ICE on thread_local check

### ISSUE THREAD

**Issue by l4l** [bjorn3/rustc_codegen_cranelift#973]
It seems I'm quite lucky with bugs, found another ICE. How to reproduce:

```bash
git clone https://github.com/Amanieu/thread_local-rs.git
$cg_clif_dir/cargo.sh check
```

<details>
  <summary>Error</summary>

```
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:754: cannot create local mono-item for DefId(15:20 ~ lazy_static[96a2]::lazy[0]::{{impl}}[0]::get[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:904:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (7f3df5772 2020-04-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z panic-abort-tests -Z codegen-backend=/home/kitsu/dev/rustc_codegen_cranelift/target/release/librustc_codegen_cranelift.so -C debuginfo=2 -C incremental -C panic=abort -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `thread_local`.
```

</details>

<details>
  <summary>Backtrace</summary>

```
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::bug_fmt
  20: rustc_mir::monomorphize::collector::should_monomorphize_locally
  21: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator_kind
  22: rustc_mir::monomorphize::collector::collect_items_rec
  23: rustc_mir::monomorphize::collector::collect_items_rec
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_session::utils::<impl rustc_session::session::Session>::time
  33: rustc_mir::monomorphize::collector::collect_crate_mono_items
  34: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  36: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  37: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  38: rustc_query_system::query::plumbing::get_query
  39: rustc_codegen_cranelift::driver::aot::run_aot
  40: rustc_codegen_cranelift::driver::codegen_crate
  41: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  42: rustc_interface::passes::start_codegen
  43: rustc_middle::ty::context::tls::enter_global
  44: rustc_interface::queries::Queries::ongoing_codegen
  45: rustc_interface::interface::run_compiler_in_existing_thread_pool
  46: scoped_tls::ScopedKey<T>::set
  47: rustc_ast::attr::with_globals
```

</details>

**Comment by l4l** [comment]
Similar issue comes from lazy_static crate with `cargo.sh check --tests`

**Comment by bjorn3** [comment]
Strange. The ICE happens before cg_clif does any actual work in a query that cg_llvm also calls.

**Comment by l4l** [comment]
`cargo.sh test` for lazy_static compiles, but all tests fail (because of #969?). Also, if run `cargo.sh test --features spin_no_std` compilation fail with the following error:

```
error[E0460]: found possibly newer version of crate `core` which `spin` depends on
 --> lazy-static.rs/src/core_lazy.rs:8:1
  |
8 | extern crate spin;
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
          crate `core`: toolchains/nightly-2020-04-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-8665d05dd7401b76.rlib
          crate `spin`: lazy-static.rs/target/x86_64-unknown-linux-gnu/debug/deps/libspin-abd3f734466a789e.rlib
```

I guess that is unrelated to problem above

**Comment by bjorn3** [comment]
Yes, I think that is #969.

**Comment by bjorn3** [comment]
Current repro:

```rust
#[macro_use]
extern crate lazy_static;

lazy_static! {
    static ref THREAD_ID_MANAGER: () = ();
}

pub struct ThreadId(usize);
impl ThreadId {
    fn new() -> ThreadId {
        &*THREAD_ID_MANAGER;
        ThreadId(0)
    }
}
thread_local!(pub static THREAD_ID: ThreadId = ThreadId::new());
```

**Comment by bjorn3** [comment]
Current repro:

```rust
//- lazy_static/lib.rs
pub struct Lazy;

impl Lazy {
    pub fn get(&'static self) -> &() {
        loop {}
    }
}

unsafe impl Sync for Lazy {}

//- thread_local/lib.rs
extern crate lazy_static;

#[allow(non_camel_case_types)]
struct THREAD_ID_MANAGER_TYPE;

static THREAD_ID_MANAGER: THREAD_ID_MANAGER_TYPE = THREAD_ID_MANAGER_TYPE;
impl std::ops::Deref for THREAD_ID_MANAGER_TYPE {
    type Target = ();
    fn deref(&self) -> &() {
        static LAZY: lazy_static::Lazy = lazy_static::Lazy;
        LAZY.get()
    }
}

thread_local!(pub static THREAD_ID: () = {
    &*THREAD_ID_MANAGER;
});

**Comment by bjorn3** [comment]
Minimal repro:

```rust
//- lazy_static/lib.rs
pub fn get() {
    loop {}
}

//- thread_local/lib.rs
extern crate lazy_static;

pub const THREAD_ID: fn() = lazy_static::get;
```

**Comment by bjorn3** [comment]
Opened https://github.com/rust-lang/rust/issues/71293.

**Comment by bjorn3** [comment]
The problem was that I hadn't implemented check mode yet.
